service:
  extensions: [jaeger_storage, jaeger_query, healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger

extensions:
  healthcheckv2:
    use_v2: true
    http:

  jaeger_storage:
    backends:
      memstore:
        memory:
          max_traces: 100000

  jaeger_query:
    storage:
      traces: memstore

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore
